---
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# see https://docs.coderabbit.ai/reference/configuration for details
language: "en"
early_access: false

enable_free_tier: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: false
  high_level_summary_in_walkthrough: false
  poem: false
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: false
    drafts: false

chat:
  auto_reply: false

# validate at https://docs.coderabbit.ai/configuration/yaml-validator
