baseURL = 'https://nespeshnye.com/'
languageCode = 'ru-ru'
title = 'NESPESHNYE'
theme = 'ananke'

[params]
  # Указываем путь к нашему новому файлу в папке static
  custom_css = ["css/style.css"]
  
  # Оставляем эти параметры пустыми, чтобы работал ТОЛЬКО ваш CSS
  background_color_class = ""
  body_classes = ""