baseURL = 'https://nespeshnye.com/'
languageCode = 'ru-ru'
title = 'NESPESHNYE'
theme = 'ananke'

[params]
  custom_css = ["css/style.css"]
  # Оставляем пустым, чтобы тема не навязывала свои "черно-белые" полосы
  background_color_class = ""
  body_classes = ""